# Generated by Django 3.2.4 on 2021-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_countrydata_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='geojson',
            field=models.JSONField(max_length=12000),
        ),
    ]
