# Generated by Django 3.2.4 on 2021-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_countrydata_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
